config/routes.rb
Rails.application.routes.draw do
  get 'invitations/create'
  get 'invitations/update'
  get 'invitations/destroy'
  devise_for :users
  root 'events#index'

  resources :users, only: %i[show] 
  resources :events do
    resources :invitations, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :invitations
  has_many :invited, through: :invitations, class_name: 'User', source: :invited

  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :date, presence: true

  scope :upcoming, -> { where('date > ?', Time.now) }
  scope :past, -> { where('date < ?', Time.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :inviter, class_name: 'User'
  belongs_to :invited, class_name: 'User'
  belongs_to :event

  enum status: {
    attending: 1,
    not_attending: 0
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :sent_invites, class_name: 'Invitation', foreign_key: :inviter_id
  has_many :received_invites, class_name: 'Invitation', foreign_key: :invited_id
  has_many :invited_events, through: :received_invites, class_name: 'Event', source: :event,
            foreign_key: :invited_id

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def event_invite(event)
    received_invites.where(event_id: event.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :image_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    redirect_to root_path unless current_user == @event.creator
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    redirect_to root_path && return unless current_user == @event.creator

    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :location, :date)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_event, only: %i[new create]
  before_action :set_invitation, only: %i[update destroy]

  before_action :sanitize_invitation_params, only: %i[update]

  def new
    @event = Event.find(params[:event_id])
    redirect_to event_path(@event) and return unless @event.creator == current_user

    invited_ids = @event.invited.map(&:id)
    @uninvited = User.all.where.not(id: (invited_ids << @event.user_id))
  end

  def create
    invitation = @event.invitations.build(invitation_params)
    invitation.inviter_id = current_user.id

    invitation.save
    redirect_to event_path(@event)
  end

  def update
    @invitation.update(invitation_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @invitation.destroy
    redirect_to user_path(current_user)
  end

  private

  def sanitize_invitation_params
    params[:invitation][:status] = params[:invitation][:status].to_i
  end

  def invitation_params
    params.require(:invitation).permit(:invited_id, :status)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_invitation
    @invitation = Invitation.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="event-container">
  <div class="event">
    <h3 class="event-name">
      <%= event.name %>
    </h3>
    <p class="event-date">
      Date: <%= event.date %>
    </p>
    <p class="event-location">
      Location: <%= event.location %>
    </p>
    <p class="event-creator">
      Creator: <%= event.creator.name %>
    </p>
    <p class="event-description">
      <p>Description:</p>
      <p><%= event.description %></p>
    </p>
  </div>
  <div class="event-actions">
    <%= link_to 'Show', event %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>  

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_invited_event.html.erb
<div>
  <h3>
    <%= event.name %>
  </h3>
  <p class="event-date">
    Date:
    <%= event.date %>
  </p>
  <p class="event-location">
    Location:
    <%= event.location %>
  </p>
  <p class="event-creator">
    Creator:
    <%= event.creator.name %>
  </p>
  <p class="event-description">
    <p>Description:</p>
    <p>
      <%= event.description %>
    </p>
  </p>
  <p class="invitation_status">
    Invitation status: <%= current_user.event_invite(event).status.humanize %>
  </p>

  <%= form_with model: current_user.event_invite(event) do |form| %>
    <h3>Change invitation status</h3>
    <%= form.select :status, {'Attending' => 1, 'Not Attending' => 0 } %>
    <%= form.submit 'save' %>
  <% end %>
  
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="events-container">
  <h2 class="events-title">Upcoming Events</h2>
  <%= render @events.upcoming %>

  <h2 class="events-title">Past Events</h2>
  <%= render @events.past %>
</div>
<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @event.name %></h2>
  
<div>
  <strong>Description</strong>
  <p>
    <%= @event.description %>
  </p>
</div>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @event.creator.name %>
</p>

<ul class="event_attendees">
  <h3>Attendees</h3>
  <% @event.invited.each do | attendee | %>
    <li><%= attendee.name %></li>
  <% end %>
</ul>

<% if user_signed_in? && current_user == @event.creator %>
  <%= link_to 'Invite Attendees', new_event_invitation_path(@event) %><br>
<% end %>

<%= link_to 'Back', events_path %>
<% if user_signed_in? && current_user == @event.creator %>
  | <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/invitations/_invite.html.erb
<div class="invite-container">
  <p class="event-name"><strong><%= invite.event.name %></strong></p>
  <p class="event-owner"><strong>Creator:</strong> <%= invite.event.creator.name %></p>
  
  <%= form_with model: invite do |form| %>
    <%= form.hidden_field :accepted, value: true %>
    <%= form.submit 'accept' %>
  <% end %>
  
  <%= link_to 'reject', invite, method: :delete, data: { confirm: 'Are you sure' } %>
</div>

app/views/invitations/new.html.erb
<ul>
  <h2>People to invite</h2>
  <% @uninvited.each do |attendee| %>
    <li>
      <%= form_with model: [@event, @event.invitations.build] do |form| %>

        <%= form.hidden_field :invited_id, value: attendee.id %>
        
        <p>Name: <%= attendee.name %></p> |
        <%= form.submit 'Invite' %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= link_to root_path do %>
      <h1>Private-Events</h1>
    <% end %>

    <div class="user-actions">
      <% if user_signed_in? %>
        <%= link_to user_path(current_user) do %>
          <p class="user-name"><%= current_user.name %></p>
        <% end %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure' }%>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path %>
        <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
      
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="user-container">
  <h2 class="user-name"><%= @user.name %></h2>
  <div class="event-created">
    <h3>Events created</h3>
    <% @user.events.each do |event| %>
      <%= render partial: 'events/event', locals: { event: event } %>
    <% end %>
  </div>

  <div class="event-upcoming">
    <h3>Upcoming events</h3>
    <% @user.invited_events.upcoming.each do |event| %>
      <%= render partial: 'events/invited_event', locals: { event: event } %>
    <% end %>
  </div>

  <div>
    <h3>Past Events</h3>
    <% @user.invited_events.past.each do |event| %>
      <%= render partial: 'events/event', locals: { event: event } %>
    <% end %>
  </div>
</div>